"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {AdminShell} from "@/components/AdminShell";
import {couponAdminApi,type CouponAdminInput} from "@/lib/api/orders";
import type{ApiCoupon}from"@/lib/api/types";

const expiry=()=>new Date(Date.now()+180*24*60*60*1000).toISOString().slice(0,16);
const blank=():CouponAdminInput=>({code:"",discountType:"PERCENTAGE",discountValue:10,minimumOrderValue:0,maximumDiscount:null,expiresAt:expiry(),usageLimit:null,perCustomerLimit:1,active:true});

export function AdminCouponPanel(){
 const[coupons,setCoupons]=useState<ApiCoupon[]>([]),[draft,setDraft]=useState<CouponAdminInput|null>(null),[editing,setEditing]=useState<string|null>(null);
 const[busy,setBusy]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setBusy(true);setError("");try{setCoupons(await couponAdminApi.list())}catch(e){setError(e instanceof Error?e.message:"Could not load coupons.")}finally{setBusy(false)}},[]);
 useEffect(()=>{void Promise.resolve().then(load)},[load]);
 function edit(coupon:ApiCoupon){setEditing(coupon.id);setDraft({code:coupon.code,discountType:coupon.discountType,discountValue:coupon.discountValue,minimumOrderValue:coupon.minimumOrderValue,maximumDiscount:coupon.maximumDiscount??null,expiresAt:new Date(coupon.expiresAt).toISOString().slice(0,16),usageLimit:coupon.usageLimit??null,perCustomerLimit:coupon.perCustomerLimit??null,active:coupon.active})}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!draft)return;setBusy(true);setError("");setMessage("");const request={...draft,code:draft.code.toUpperCase(),expiresAt:new Date(draft.expiresAt).toISOString()};try{if(editing)await couponAdminApi.update(editing,request);else await couponAdminApi.create(request);setDraft(null);setEditing(null);setMessage("Coupon saved.");await load()}catch(e){setError(e instanceof Error?e.message:"Could not save coupon.")}finally{setBusy(false)}}
 async function toggle(coupon:ApiCoupon){setBusy(true);setError("");try{await couponAdminApi.update(coupon.id,{code:coupon.code,discountType:coupon.discountType,discountValue:coupon.discountValue,minimumOrderValue:coupon.minimumOrderValue,maximumDiscount:coupon.maximumDiscount??null,expiresAt:coupon.expiresAt,usageLimit:coupon.usageLimit??null,perCustomerLimit:coupon.perCustomerLimit??null,active:!coupon.active});await load()}catch(e){setError(e instanceof Error?e.message:"Could not update coupon.")}finally{setBusy(false)}}
 function number(value:string){return value===""?null:Number(value)}
 return <AdminShell title="Coupons"><div className="admin-actions"><p>Server-authoritative promotions and usage controls.</p><button className="btn-primary" disabled={busy} onClick={()=>{setEditing(null);setDraft(blank())}}>Create coupon</button></div>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="success-note" role="status">{message}</p>}
 {draft&&<form className="panel coupon-admin-form" onSubmit={save}><h2>{editing?"Edit coupon":"New coupon"}</h2><div className="form-grid"><div className="field"><label htmlFor="couponCode">CODE</label><input id="couponCode" required minLength={3} maxLength={32} pattern="[A-Za-z0-9_-]+" value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value.toUpperCase()})}/></div><div className="field"><label htmlFor="discountType">TYPE</label><select id="discountType" value={draft.discountType} onChange={e=>setDraft({...draft,discountType:e.target.value as CouponAdminInput["discountType"]})}><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed INR</option></select></div><div className="field"><label htmlFor="discountValue">DISCOUNT VALUE</label><input id="discountValue" required type="number" min="0.01" max={draft.discountType==="PERCENTAGE"?100:1000000} step="0.01" value={draft.discountValue} onChange={e=>setDraft({...draft,discountValue:Number(e.target.value)})}/></div><div className="field"><label htmlFor="minimumOrder">MINIMUM ORDER</label><input id="minimumOrder" required type="number" min="0" step="0.01" value={draft.minimumOrderValue} onChange={e=>setDraft({...draft,minimumOrderValue:Number(e.target.value)})}/></div><div className="field"><label htmlFor="maximumDiscount">MAXIMUM DISCOUNT</label><input id="maximumDiscount" type="number" min="0.01" step="0.01" value={draft.maximumDiscount??""} onChange={e=>setDraft({...draft,maximumDiscount:number(e.target.value)})}/></div><div className="field"><label htmlFor="couponExpiry">EXPIRES</label><input id="couponExpiry" required type="datetime-local" value={draft.expiresAt} onChange={e=>setDraft({...draft,expiresAt:e.target.value})}/></div><div className="field"><label htmlFor="usageLimit">TOTAL USAGE LIMIT</label><input id="usageLimit" type="number" min="1" value={draft.usageLimit??""} onChange={e=>setDraft({...draft,usageLimit:number(e.target.value)})}/></div><div className="field"><label htmlFor="customerLimit">PER-CUSTOMER LIMIT</label><input id="customerLimit" type="number" min="1" value={draft.perCustomerLimit??""} onChange={e=>setDraft({...draft,perCustomerLimit:number(e.target.value)})}/></div></div><label className="check-row"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Coupon active</label><div className="form-actions"><button className="btn-primary" disabled={busy}>Save coupon</button><button className="btn-quiet" type="button" onClick={()=>setDraft(null)}>Cancel</button></div></form>}
 <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Code</th><th>Offer</th><th>Eligibility</th><th>Expiry</th><th>Usage</th><th>Actions</th></tr></thead><tbody>{coupons.map(coupon=><tr key={coupon.id}><td><b>{coupon.code}</b><br/><small>{coupon.active?"Active":"Inactive"}</small></td><td>{coupon.discountType==="PERCENTAGE"?`${coupon.discountValue}%`:`₹${coupon.discountValue}`}{coupon.maximumDiscount?<><br/><small>Cap ₹{coupon.maximumDiscount}</small></>:null}</td><td>Min ₹{coupon.minimumOrderValue}<br/><small>{coupon.perCustomerLimit??"∞"} per customer</small></td><td>{new Date(coupon.expiresAt).toLocaleDateString("en-IN")}</td><td>{coupon.usageCount}{coupon.usageLimit?` / ${coupon.usageLimit}`:""}</td><td><button disabled={busy} onClick={()=>edit(coupon)}>Edit</button> <button disabled={busy} onClick={()=>void toggle(coupon)}>{coupon.active?"Disable":"Enable"}</button></td></tr>)}</tbody></table>{!busy&&!coupons.length&&<p>No coupons configured.</p>}</div></AdminShell>
}
