"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/context/auth";
import { ApiError } from "@/lib/api/client";

const copy={login:["Welcome back","Sign in to continue your ShopSphere journey","Sign in"],register:["Create your account","One account. A whole sphere of possibilities.","Create account"],forgot:["Forgot your password?","Password reset is not enabled yet. Contact ShopSphere support.","Back to sign in"],reset:["Set a new password","Password reset is not enabled yet. Contact ShopSphere support.","Back to sign in"]};
export function AuthForm({mode}:{mode:keyof typeof copy}){
 const info=copy[mode],{login,register}=useAuth(),router=useRouter();const[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(mode==="forgot"||mode==="reset"){router.push("/login");return}const data=new FormData(event.currentTarget);setBusy(true);setError("");try{const user=mode==="login"?await login(String(data.get("email")),String(data.get("password"))):await register({firstName:String(data.get("firstName")),lastName:String(data.get("lastName")),email:String(data.get("email")),password:String(data.get("password")),phone:String(data.get("phone")||"")||undefined});const destination=new URLSearchParams(window.location.search).get("returnTo");router.replace(destination?.startsWith("/")?destination:user.role==="ADMIN"?"/admin":"/account")}catch(e){setError(e instanceof ApiError?e.message:"Unable to continue. Please retry.")}finally{setBusy(false)}}
 return <div className="auth-wrap"><form className="auth-card" onSubmit={submit}><Link className="logo" href="/"><b>SHOP</b><i>SPHERE</i></Link><h1>{info[0]}</h1><p>{info[1]}</p>{mode==="register"&&<><div className="field"><label htmlFor="firstName">FIRST NAME</label><input id="firstName" name="firstName" required autoComplete="given-name"/></div><div className="field"><label htmlFor="lastName">LAST NAME</label><input id="lastName" name="lastName" required autoComplete="family-name"/></div><div className="field"><label htmlFor="phone">PHONE (optional)</label><input id="phone" name="phone" autoComplete="tel"/></div></>}<div className="field"><label htmlFor="email">EMAIL ADDRESS</label><input id="email" name="email" type="email" required autoComplete="email" placeholder="name@example.com"/></div>{mode!=="forgot"&&<div className="field"><label htmlFor="password">{mode==="reset"?"NEW PASSWORD":"PASSWORD"}</label><input id="password" name="password" type="password" required minLength={8} autoComplete={mode==="login"?"current-password":"new-password"} placeholder="At least 8 characters"/></div>}{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn-primary" type="submit" disabled={busy}>{busy?"Please wait…":info[2]}</button><div className="auth-links">{mode==="login"?<><Link href="/register">Create account</Link><Link href="/forgot-password">Forgot password?</Link></>:<Link href="/login">← Back to sign in</Link>}</div><small>By continuing, you agree to ShopSphere’s Terms and Privacy Notice.</small></form></div>
}
