"use client";
import { createContext,useCallback,useContext,useEffect,useMemo,useRef,useState } from "react";
import { useAuth } from "@/context/auth";import { cartApi } from "@/lib/api/cart";import { productApi } from "@/lib/api/products";import { toProduct } from "@/lib/api/mappers";import type { ApiCart } from "@/lib/api/types";import type { CartItem,Product } from "@/types";
const GUEST_CART="ss-cart",WISHLIST="ss-wishlist";
type Store={cart:CartItem[];wishlist:Product[];cartCount:number;busy:boolean;error:string|null;addToCart:(p:Product)=>Promise<void>;updateQty:(id:string,n:number)=>Promise<void>;removeFromCart:(id:string)=>Promise<void>;toggleWishlist:(p:Product)=>void;inWishlist:(id:string)=>boolean;clearCart:()=>Promise<void>;refreshCart:()=>Promise<void>};
const Context=createContext<Store|null>(null);
const fallback=(i:ApiCart["items"][number]):Product=>({id:i.productId,title:i.productName,brand:"ShopSphere",category:"",image:i.imageUrl||"/media/cat-deals.jpg",images:[i.imageUrl||"/media/cat-deals.jpg"],rating:0,reviewCount:0,originalPrice:i.unitPrice,price:i.unitPrice,delivery:"Delivery details shown at checkout",stock:0,description:"",specs:{}});
export function StoreProvider({children}:{children:React.ReactNode}){const{user,loading:authLoading}=useAuth();const[cart,setCart]=useState<CartItem[]>([]),[wishlist,setWishlist]=useState<Product[]>([]);const[ready,setReady]=useState(false),[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const merged=useRef<string|null>(null);
 useEffect(()=>{Promise.resolve().then(()=>{try{setCart(JSON.parse(localStorage.getItem(GUEST_CART)||"[]"));setWishlist(JSON.parse(localStorage.getItem(WISHLIST)||"[]"))}catch{localStorage.removeItem(GUEST_CART);localStorage.removeItem(WISHLIST)}finally{setReady(true)}})},[]);
 useEffect(()=>{if(ready&&!user&&!authLoading&&merged.current===null)localStorage.setItem(GUEST_CART,JSON.stringify(cart))},[cart,ready,user,authLoading]);useEffect(()=>{if(ready)localStorage.setItem(WISHLIST,JSON.stringify(wishlist))},[wishlist,ready]);
 const hydrate=useCallback(async(source:ApiCart)=>{setCart(await Promise.all(source.items.map(async i=>{try{return{product:toProduct(await productApi.get(i.productId)),quantity:i.quantity}}catch{return{product:fallback(i),quantity:i.quantity}}})))},[]);
 const refreshCart=useCallback(async()=>{if(!user)return;setBusy(true);try{setError(null);await hydrate(await cartApi.get(user.id))}catch(e){setError(e instanceof Error?e.message:"Could not load your cart.")}finally{setBusy(false)}},[hydrate,user]);
 useEffect(()=>{if(authLoading||!ready)return;if(!user){if(merged.current){merged.current=null;Promise.resolve().then(()=>setCart([]));localStorage.removeItem(GUEST_CART);}return}if(merged.current===user.id)return;merged.current=user.id;const guest:CartItem[]=JSON.parse(localStorage.getItem(GUEST_CART)||"[]");setBusy(true);setError(null);(async()=>{try{for(const item of guest)await cartApi.add(user.id,item.product.id,item.quantity);localStorage.removeItem(GUEST_CART);await hydrate(await cartApi.get(user.id))}catch(e){setError(e instanceof Error?e.message:"Could not synchronize your cart.")}finally{setBusy(false)}})();
 // This transition intentionally runs once for each authenticated user.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[authLoading,ready,user?.id,hydrate]);
 const addToCart=useCallback(async(p:Product)=>{if(!user){setCart(c=>c.some(i=>i.product.id===p.id)?c.map(i=>i.product.id===p.id?{...i,quantity:i.quantity+1}:i):[...c,{product:p,quantity:1}]);return}setBusy(true);try{setError(null);await hydrate(await cartApi.add(user.id,p.id,1))}catch(e){setError(e instanceof Error?e.message:"Could not add this item.");throw e}finally{setBusy(false)}},[hydrate,user]);
 const updateQty=useCallback(async(id:string,n:number)=>{if(!user){setCart(c=>n<1?c.filter(i=>i.product.id!==id):c.map(i=>i.product.id===id?{...i,quantity:n}:i));return}setBusy(true);try{await hydrate(n<1?await cartApi.remove(user.id,id):await cartApi.update(user.id,id,n))}finally{setBusy(false)}},[hydrate,user]);
 const removeFromCart=useCallback(async(id:string)=>{if(!user){setCart(c=>c.filter(i=>i.product.id!==id));return}setBusy(true);try{await hydrate(await cartApi.remove(user.id,id))}finally{setBusy(false)}},[hydrate,user]);
 const clearCart=useCallback(async()=>{if(user)await cartApi.clear(user.id);setCart([])},[user]);const toggleWishlist=useCallback((p:Product)=>setWishlist(w=>w.some(i=>i.id===p.id)?w.filter(i=>i.id!==p.id):[...w,p]),[]);
 const value=useMemo<Store>(()=>({cart,wishlist,cartCount:cart.reduce((n,i)=>n+i.quantity,0),busy,error,addToCart,updateQty,removeFromCart,toggleWishlist,inWishlist:id=>wishlist.some(p=>p.id===id),clearCart,refreshCart}),[cart,wishlist,busy,error,addToCart,updateQty,removeFromCart,toggleWishlist,clearCart,refreshCart]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const useStore=()=>{const value=useContext(Context);if(!value)throw new Error("useStore requires StoreProvider");return value};
