"use client";
import { Suspense,useEffect,useState } from "react";
import { useRouter,useSearchParams } from "next/navigation";
import { ProductCard } from "@/components/ProductCard";
import { productApi } from "@/lib/api/products";
import { toProduct } from "@/lib/api/mappers";
import type { Product } from "@/types";
function Results(){
 const params=useSearchParams(),router=useRouter();const[items,setItems]=useState<Product[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");const q=params.get("q")?.trim()||undefined,category=params.get("category")||undefined,sort=params.get("sort")||"relevance",page=Math.max(0,Number(params.get("page")||0));
 useEffect(()=>{let current=true;Promise.resolve().then(()=>{if(current){setLoading(true);setError("")}});productApi.list({q,category,sort,page,size:12}).then(p=>{if(current){setItems(p.content.map(toProduct));setTotal(p.totalElements)}}).catch(e=>{if(current)setError(e instanceof Error?e.message:"Catalog unavailable")}).finally(()=>{if(current)setLoading(false)});return()=>{current=false}},[q,category,sort,page]);
 function update(name:string,value:string){const next=new URLSearchParams(params.toString());if(value)next.set(name,value);else next.delete(name);if(name!=="page")next.delete("page");router.push(`/search?${next}`)}
 const pages=Math.ceil(total/12);return <div className="page-wrap search-page"><div className="breadcrumb">Home / Catalog</div><h1 className="page-title">{q?`Results for “${q}”`:category||"Explore all products"}</h1><div className="results-top"><span>{loading?"Loading…":`${total} products`}</span><select value={sort} onChange={e=>update("sort",e.target.value)} aria-label="Sort products"><option value="relevance">Relevance</option><option value="newest">Newest first</option><option value="price_asc">Price: Low to high</option><option value="price_desc">Price: High to low</option><option value="rating">Customer rating</option></select></div>{error?<div className="state-card" role="alert"><h2>Catalog unavailable</h2><p>{error}</p><button className="btn-primary" onClick={()=>location.reload()}>Retry</button></div>:loading?<div className="state-card" role="status">Loading products…</div>:items.length?<><div className="results-grid">{items.map(p=><ProductCard key={p.id} product={p}/>)}</div>{pages>1&&<nav className="pagination" aria-label="Search pages">{Array.from({length:pages},(_,i)=><button key={i} className={i===page?"selected":""} onClick={()=>update("page",String(i))}>{i+1}</button>)}</nav>}</>:<div className="empty"><div className="symbol">⌕</div><h2>No matching products</h2><p>Try a broader search or explore all categories.</p></div>}</div>
}
export default function SearchPage(){return <Suspense fallback={<div className="page-wrap"><div className="state-card">Loading products…</div></div>}><Results/></Suspense>}
