"use client";

import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {RequireAuth} from "@/components/RequireAuth";
import {useAuth} from "@/context/auth";

function Content(){
 const{user,updateProfile,changePassword,logout}=useAuth();
 const[firstName,setFirstName]=useState(""),[lastName,setLastName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState("");
 const[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[passwordBusy,setPasswordBusy]=useState(false),[passwordMessage,setPasswordMessage]=useState(""),[passwordError,setPasswordError]=useState("");
 useEffect(()=>{if(user)Promise.resolve().then(()=>{setFirstName(user.firstName);setLastName(user.lastName);setEmail(user.email);setPhone(user.phone??"")})},[user]);
 async function saveProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");setError("");try{await updateProfile({firstName,lastName,email,phone:phone||null});setMessage("Your profile has been updated.")}catch(e){setError(e instanceof Error?e.message:"Could not update your profile.")}finally{setBusy(false)}}
 async function savePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),next=String(data.get("newPassword")),confirm=String(data.get("confirmPassword"));setPasswordMessage("");setPasswordError("");if(next!==confirm){setPasswordError("New passwords do not match.");return}setPasswordBusy(true);try{await changePassword(String(data.get("currentPassword")),next);form.reset();setPasswordMessage("Password changed securely.")}catch(e){setPasswordError(e instanceof Error?e.message:"Could not change your password.")}finally{setPasswordBusy(false)}}
 return <div className="page-wrap account-page"><div className="page-heading-row"><div><small className="eyebrow">YOUR ACCOUNT</small><h1 className="page-title">Hello, {user?.firstName}</h1><p>Manage your identity and delivery preferences.</p></div><span className="account-since">Customer since {user?.createdAt?new Date(user.createdAt).toLocaleDateString("en-IN",{month:"long",year:"numeric"}):"—"}</span></div>
 <div className="profile-grid"><aside className="profile-nav"><b>Account menu</b><Link className="active" href="/account">Profile</Link><Link href="/account/addresses">Saved addresses</Link><Link href="/orders">My orders</Link><Link href="/wishlist">Wishlist</Link>{user?.role==="ADMIN"&&<Link href="/admin">Admin console</Link>}<Link href="/login" onClick={logout}>Sign out</Link></aside>
 <section className="account-content"><form className="panel profile-form" onSubmit={saveProfile}><div className="panel-title"><div><small>PERSONAL DETAILS</small><h2>Profile information</h2></div><span>Private to your account</span></div>
 <div className="form-grid"><div className="field"><label htmlFor="firstName">FIRST NAME</label><input id="firstName" required minLength={1} maxLength={80} pattern="[^0-9]+" autoComplete="given-name" value={firstName} onChange={e=>setFirstName(e.target.value)}/></div><div className="field"><label htmlFor="lastName">LAST NAME</label><input id="lastName" required minLength={1} maxLength={80} pattern="[^0-9]+" autoComplete="family-name" value={lastName} onChange={e=>setLastName(e.target.value)}/></div><div className="field"><label htmlFor="profileEmail">EMAIL</label><input id="profileEmail" type="email" required maxLength={320} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label htmlFor="profilePhone">PHONE</label><input id="profilePhone" type="tel" pattern="[+0-9 ()-]{7,20}" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></div></div>
 {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="success-note" role="status">{message}</p>}<button className="btn-primary" disabled={busy}>{busy?"Saving…":"Save profile"}</button></form>
 <form className="panel password-form" onSubmit={savePassword}><div className="panel-title"><div><small>SECURITY</small><h2>Change password</h2></div></div><div className="form-grid"><div className="field"><label htmlFor="currentPassword">CURRENT PASSWORD</label><input id="currentPassword" name="currentPassword" type="password" required autoComplete="current-password"/></div><div className="field"><label htmlFor="newPassword">NEW PASSWORD</label><input id="newPassword" name="newPassword" type="password" required minLength={8} maxLength={72} autoComplete="new-password"/></div><div className="field"><label htmlFor="confirmPassword">CONFIRM NEW PASSWORD</label><input id="confirmPassword" name="confirmPassword" type="password" required minLength={8} maxLength={72} autoComplete="new-password"/></div></div>{passwordError&&<p className="form-error" role="alert">{passwordError}</p>}{passwordMessage&&<p className="success-note" role="status">{passwordMessage}</p>}<button className="btn-secondary account-action" disabled={passwordBusy}>{passwordBusy?"Updating…":"Update password"}</button></form></section></div></div>
}
export default function Account(){return <RequireAuth><Content/></RequireAuth>}
