{
 "title": "ShopSphere Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Service availability",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "up{job=\"shopsphere\"}",
     "legendFormat": "{{instance}} {{routeId}} {{name}} {{state}}"
    }
   ]
  },
  {
   "title": "Requests / second",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{instance}} {{routeId}} {{name}} {{state}}"
    }
   ]
  },
  {
   "title": "HTTP p95 seconds",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum by(le,instance) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "{{instance}} {{routeId}} {{name}} {{state}}"
    }
   ]
  },
  {
   "title": "Gateway routes",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(routeId) (rate(spring_cloud_gateway_requests_seconds_count[5m]))",
     "legendFormat": "{{instance}} {{routeId}} {{name}} {{state}}"
    }
   ]
  },
  {
   "title": "JVM heap bytes",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{instance}} {{routeId}} {{name}} {{state}}"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads",
     "legendFormat": "{{instance}} {{routeId}} {{name}} {{state}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "process_cpu_usage",
     "legendFormat": "{{instance}} {{routeId}} {{name}} {{state}}"
    }
   ]
  },
  {
   "title": "5xx / second",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))",
     "legendFormat": "{{instance}} {{routeId}} {{name}} {{state}}"
    }
   ]
  },
  {
   "title": "Circuit breakers",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 32, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state",
     "legendFormat": "{{instance}} {{routeId}} {{name}} {{state}}"
    }
   ]
  }
 ]
}