#!/bin/bash
set -eu
mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${AUTH_DB_NAME}\`;
CREATE DATABASE IF NOT EXISTS \`${INVENTORY_DB_NAME}\`;
CREATE DATABASE IF NOT EXISTS \`${ORDER_DB_NAME}\`;
CREATE USER IF NOT EXISTS '${AUTH_DB_USERNAME}'@'%' IDENTIFIED BY '${AUTH_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${INVENTORY_DB_USERNAME}'@'%' IDENTIFIED BY '${INVENTORY_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${ORDER_DB_USERNAME}'@'%' IDENTIFIED BY '${ORDER_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${AUTH_DB_NAME}\`.* TO '${AUTH_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON \`${INVENTORY_DB_NAME}\`.* TO '${INVENTORY_DB_USERNAME}'@'%';
GRANT ALL PRIVILEGES ON \`${ORDER_DB_NAME}\`.* TO '${ORDER_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
SQL
