"use client";

import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {RequireAuth} from "@/components/RequireAuth";
import {addressApi,type AddressInput} from "@/lib/api/addresses";
import type{ApiSavedAddress}from"@/lib/api/types";

const blank:AddressInput={recipientName:"",phone:"",line1:"",line2:"",city:"",state:"",postalCode:"",country:"India",defaultAddress:false};

function Content(){
 const[addresses,setAddresses]=useState<ApiSavedAddress[]>([]),[draft,setDraft]=useState<AddressInput>(blank),[editing,setEditing]=useState<string|null>(null);
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{setAddresses(await addressApi.list())}catch(e){setError(e instanceof Error?e.message:"Could not load saved addresses.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void Promise.resolve().then(load)},[load]);
 function edit(address:ApiSavedAddress){setEditing(address.id);setDraft({recipientName:address.recipientName,phone:address.phone,line1:address.line1,line2:address.line2??"",city:address.city,state:address.state,postalCode:address.postalCode,country:address.country,defaultAddress:address.defaultAddress});setMessage("");window.scrollTo({top:0,behavior:"smooth"})}
 function cancel(){setEditing(null);setDraft(blank);setError("")}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setMessage("");try{if(editing)await addressApi.update(editing,draft);else await addressApi.add(draft);setMessage(editing?"Address updated.":"Address saved.");setEditing(null);setDraft(blank);await load()}catch(e){setError(e instanceof Error?e.message:"Could not save the address.")}finally{setBusy(false)}}
 async function makeDefault(id:string){setBusy(true);setError("");try{await addressApi.setDefault(id);setMessage("Default delivery address updated.");await load()}catch(e){setError(e instanceof Error?e.message:"Could not set the default address.")}finally{setBusy(false)}}
 async function remove(address:ApiSavedAddress){if(!confirm(`Delete the address at ${address.line1}?`))return;setBusy(true);setError("");try{await addressApi.remove(address.id);setMessage("Address deleted.");if(editing===address.id){setEditing(null);setDraft(blank)}await load()}catch(e){setError(e instanceof Error?e.message:"Could not delete the address.")}finally{setBusy(false)}}
 function field<K extends keyof AddressInput>(key:K,value:AddressInput[K]){setDraft(current=>({...current,[key]:value}))}
 return <div className="page-wrap address-page"><div className="breadcrumb"><Link href="/account">Account</Link> / Saved addresses</div><div className="page-heading-row"><div><small className="eyebrow">DELIVERY</small><h1 className="page-title">Saved addresses</h1><p>Choose a default address for a faster, safer checkout.</p></div><span className="address-count">{addresses.length}/10 saved</span></div>
 <div className="address-layout"><form className="panel address-form" onSubmit={save}><div className="panel-title"><div><small>{editing?"EDIT ADDRESS":"NEW ADDRESS"}</small><h2>{editing?"Update delivery details":"Add a delivery address"}</h2></div></div>
 <div className="form-grid"><div className="field full"><label htmlFor="recipientName">RECIPIENT NAME</label><input id="recipientName" required maxLength={120} autoComplete="name" value={draft.recipientName} onChange={e=>field("recipientName",e.target.value)}/></div><div className="field"><label htmlFor="addressPhone">PHONE</label><input id="addressPhone" required type="tel" pattern="[+0-9 ()-]{7,20}" autoComplete="tel" value={draft.phone} onChange={e=>field("phone",e.target.value)}/></div><div className="field"><label htmlFor="postalCode">POSTAL CODE</label><input id="postalCode" required minLength={3} maxLength={20} autoComplete="postal-code" value={draft.postalCode} onChange={e=>field("postalCode",e.target.value)}/></div><div className="field full"><label htmlFor="line1">ADDRESS LINE 1</label><input id="line1" required maxLength={255} autoComplete="address-line1" value={draft.line1} onChange={e=>field("line1",e.target.value)}/></div><div className="field full"><label htmlFor="line2">ADDRESS LINE 2 <span>(optional)</span></label><input id="line2" maxLength={255} autoComplete="address-line2" value={draft.line2} onChange={e=>field("line2",e.target.value)}/></div><div className="field"><label htmlFor="city">CITY</label><input id="city" required maxLength={100} autoComplete="address-level2" value={draft.city} onChange={e=>field("city",e.target.value)}/></div><div className="field"><label htmlFor="state">STATE</label><input id="state" required maxLength={100} autoComplete="address-level1" value={draft.state} onChange={e=>field("state",e.target.value)}/></div><div className="field full"><label htmlFor="country">COUNTRY</label><input id="country" required maxLength={100} autoComplete="country-name" value={draft.country} onChange={e=>field("country",e.target.value)}/></div></div>
 <label className="check-row"><input type="checkbox" checked={draft.defaultAddress} onChange={e=>field("defaultAddress",e.target.checked)}/> Make this my default address</label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="btn-primary" disabled={busy}>{busy?"Saving…":editing?"Update address":"Save address"}</button>{editing&&<button className="btn-quiet" type="button" onClick={cancel}>Cancel</button>}</div></form>
 <section className="address-list" aria-busy={loading}>{message&&<p className="success-note" role="status">{message}</p>}{loading?<div className="state-card">Loading your addresses…</div>:!addresses.length?<div className="empty compact"><h2>No addresses saved</h2><p>Add your first delivery address to continue to checkout.</p></div>:addresses.map(address=><article className={`address-card ${address.defaultAddress?"default":""}`} key={address.id}><div className="address-card-head"><b>{address.recipientName}</b>{address.defaultAddress&&<span>Default</span>}</div><p>{address.line1}{address.line2&&<><br/>{address.line2}</>}<br/>{address.city}, {address.state} {address.postalCode}<br/>{address.country}</p><small>{address.phone}</small><div className="address-actions"><button className="btn-quiet" disabled={busy} onClick={()=>edit(address)}>Edit</button>{!address.defaultAddress&&<button className="btn-quiet" disabled={busy} onClick={()=>void makeDefault(address.id)}>Set default</button>}<button className="link-btn danger" disabled={busy} onClick={()=>void remove(address)}>Delete</button></div></article>)}</section></div></div>
}

export default function Addresses(){return <RequireAuth><Content/></RequireAuth>}
